/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/primeiro-acesso`; params?: Router.UnknownInputParams; } | { pathname: `/../vite.config`; params?: Router.UnknownInputParams; } | { pathname: `/../src/config/env`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/useMediaQuery`; params?: Router.UnknownInputParams; } | { pathname: `/../src/main`; params?: Router.UnknownInputParams; } | { pathname: `/../src/App`; params?: Router.UnknownInputParams; } | { pathname: `/../src/routes/ProtectedRoute`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/pages/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/../src/pages/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/../src/pages/PrimeiroAcessoPage`; params?: Router.UnknownInputParams; } | { pathname: `/../src/pages/NotasPage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notas` | `/notas`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/primeiro-acesso`; params?: Router.UnknownOutputParams; } | { pathname: `/../vite.config`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/config/env`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/hooks/useMediaQuery`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/main`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/App`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/routes/ProtectedRoute`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/LoadingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/pages/HomePage`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/pages/LoginPage`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/pages/PrimeiroAcessoPage`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/pages/NotasPage`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/notas` | `/notas`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/primeiro-acesso${`?${string}` | `#${string}` | ''}` | `/../vite.config${`?${string}` | `#${string}` | ''}` | `/../src/config/env${`?${string}` | `#${string}` | ''}` | `/../src/hooks/useMediaQuery${`?${string}` | `#${string}` | ''}` | `/../src/main${`?${string}` | `#${string}` | ''}` | `/../src/App${`?${string}` | `#${string}` | ''}` | `/../src/routes/ProtectedRoute${`?${string}` | `#${string}` | ''}` | `/../src/components/LoadingScreen${`?${string}` | `#${string}` | ''}` | `/../src/pages/HomePage${`?${string}` | `#${string}` | ''}` | `/../src/pages/LoginPage${`?${string}` | `#${string}` | ''}` | `/../src/pages/PrimeiroAcessoPage${`?${string}` | `#${string}` | ''}` | `/../src/pages/NotasPage${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/notas${`?${string}` | `#${string}` | ''}` | `/notas${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/primeiro-acesso`; params?: Router.UnknownInputParams; } | { pathname: `/../vite.config`; params?: Router.UnknownInputParams; } | { pathname: `/../src/config/env`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/useMediaQuery`; params?: Router.UnknownInputParams; } | { pathname: `/../src/main`; params?: Router.UnknownInputParams; } | { pathname: `/../src/App`; params?: Router.UnknownInputParams; } | { pathname: `/../src/routes/ProtectedRoute`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/pages/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/../src/pages/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/../src/pages/PrimeiroAcessoPage`; params?: Router.UnknownInputParams; } | { pathname: `/../src/pages/NotasPage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notas` | `/notas`; params?: Router.UnknownInputParams; };
    }
  }
}
